### ISSUE TITLE
More history?

### ISSUE THREAD

**Issue by thisisloze** [ciphyr/TradingView-data-scraper#2]
I'm getting about ~800 data points for history.
Any possibly way to grab all points from a chart?
A way to use this on a chart rather then an idea?

**Comment by ciphyr** [comment]
@thisisloze 
Pan backwards on the chart before you publish, or just use the GOTO function to search for a date long ago. This will load all data since the last-available date. THEN click publish, your published chart will have a longer history and so will the CSV when you scrape it.

Made a quick video tutorial: https://cl.ly/195183
